### ISSUE TITLE
Certificate error

### ISSUE THREAD

**Issue by ShadySQL** [Microsoft/vsts-agent#1341]
Agent Version: 2.119.1

2017-12-21T18:27:41.2150717Z ##[error]Failed in getBuild with error: Error: unable to get local issuer certificate
2017-12-21T18:27:41.2306911Z ##[error]{"stack":"Error: unable to get local issuer certificate\n    at Error (native)\n    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)\n    at emitNone (events.js:86:13)\n    at TLSSocket.emit (events.js:185:7)\n    at TLSSocket._finishInit (_tls_wrap.js:610:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)","message":"unable to get local issuer certificate","code":"UNABLE_TO_GET_ISSUER_CERT_LOCALLY"}
2017-12-21T18:27:41.2306911Z ##[error]Error: unable to get local issuer certificate

**Comment by TingluoHuang** [comment]
@ShadySQL does your agents connect to VSTS or TFS? if connect to TFS, have you check with your TFS admin to see whether they changed the TFS SSL certificate recently?

**Comment by ShadySQL** [comment]
I'am using VSTS.

**Comment by TingluoHuang** [comment]
@ShadySQL what's your VSTS account? do you have any http proxy or load balancer between your build agent machine and VSTS?

**Comment by ShadySQL** [comment]
I followed this guide:

https://blogs.msdn.microsoft.com/phkelley/2014/01/20/adding-a-corporate-or-self-signed-certificate-authority-to-git-exes-store/

I have three agents running on one machine and they all have the same ca bundle so I created a new directory and moved it there and then ran a git config to point to it, such as:

git config --global http.sslCAInfo D:\test\cert\ca-bundle.crt

**Comment by TingluoHuang** [comment]
@ShadySQL I think that blog post is for On-Prem TFS

**Comment by ShadySQL** [comment]
network team placed a proxy and now I am using a .proxy file for the agent with the name of the proxy.

**Comment by ShadySQL** [comment]
DO I even need to do that? Adding that:

git config --global http.sslCAInfo D:\test\cert\ca-bundle.crt

I appended the root cert from our VSTS server

**Comment by TingluoHuang** [comment]
@ShadySQL 
base on what you described, you are using TFS not VSTS.
VSTS is the cloud version of TFS, and the instance is hosted in Azure

On-Prem TFS is the one that you are using and the server is hosted on your private network.

Can you access your TFS site from IE on those build machine without hitting certificate error?

Check with your network team see whether the proxy they added will try to decrypt the https traffic, like Fiddler does? if so, you need to install the proxy's root certificate into your build machine's cert store.

**Comment by ShadySQL** [comment]
<img width="197" alt="screen shot 2017-12-21 at 22 47 14" src="https://user-images.githubusercontent.com/7299059/34272330-ec5a7276-e6a0-11e7-8454-88e2d1644570.png">

**Comment by ShadySQL** [comment]
I can 1000% guarantee is VSTS

**Comment by TingluoHuang** [comment]
OK, 
Can you access your VSTS account from IE/Chrome on those build machine without hitting certificate error?

Check with your network team see whether the proxy they added will try to decrypt the https traffic, like Fiddler does? if so, you need to install the proxy's root certificate into your build machine's cert store.

**Comment by TingluoHuang** [comment]
what's your full VSTS account name?

**Comment by ShadySQL** [comment]
Its sensitive - are you an MS employee?

**Comment by ShadySQL** [comment]
Check with your network team see whether the proxy they added will try to decrypt the https traffic, like Fiddler does? if so, you need to install the proxy's root certificate into your build machine's cert store.

**_Yes this is what they are trying to do!_**

**Comment by TingluoHuang** [comment]
did you install the proxy root cert into machine store?

**Comment by ShadySQL** [comment]
no I havent...I need to try it tomorrow and get back at this to see if I have made any progress or if the issues persists.

**Comment by TingluoHuang** [comment]
i am a MS employee. you can send any information that you think is sensitive to `tihuang@microsoft.com`

**Comment by TingluoHuang** [comment]
if the agent is working fine before they add the proxy, and now all agents start hitting the security error, plus the proxy is trying to decrypt HTTPS traffic. 
Then install the proxy root cert into the machine's certificate store should fix the agent itself, but you might still need extra step to make git.exe work.
```
git config --global http."https://yourvsts.visualstudio.com/".sslCAInfo proxyroot.pem
```
https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting#git

**Comment by ShadySQL** [comment]
OK I will try that once the folks give me the cert and proceed investigating.

**Comment by TingluoHuang** [comment]
BTW, is there a really good reason to have a proxy that decrypt HTTPS traffic in your environment?
it may cause extra problem to some tools you used during your build, like Nuget, Npm, etc.

**Comment by ShadySQL** [comment]
I installed all the proxy certificates in the machine and the error persists. I also installed Google Chrome on the machine and I am not able to reach my VSTS subscription. 

Its much more involved than this and I think the network team needs to get busy however any other advice would be helpful.

**Comment by TingluoHuang** [comment]
@ShadySQL what cert error you get when you try to access your VSTS account in browser?

**Comment by ShadySQL** [comment]
OK so installing the FW/Proxy certificates in the machine did not fix this. @TingluoHuang for some servers I'am getting an SSL error when I open up a browser but on some others I dont - in both cases I am still not able to get this to work.

**Comment by serhit** [comment]
Interesting note: one agent is configured to connect VSTS through the proxy. 
This agent may run build and publish build artifact (i.e. no problems with SSL while doing git fetch, and call to API that publishes build result). 
However, the same agent fails to download artifact it has just uploaded with "unable to get local issuer certificate"

Is processes of upload artifact and download artifact has different logic of certificates handling (different stores ?)

**Comment by TingluoHuang** [comment]
@serhit what's your agent version? can you share the error log for download artifact?

**Comment by serhit** [comment]
Agent version: 2.119.1;
Download Build Artifacts task version: 0.127.5

Log for download of artifact is attached (release name, account, and proxy server details are removed)
[4_Download artifact - release_name.log](https://github.com/Microsoft/vsts-agent/files/1586846/4_Download.artifact.-.release_name.log)

**Comment by serhit** [comment]
@TingluoHuang, additional details. 
Agents are also capible to execute simple release scenario with inline powershell scripts - script definition is downloaded successfully through the proxy. Still issue is only with downloading the build artifacts.

**Comment by serhit** [comment]
I think we may close this topic. We sorted things with our networking team (agreed to disable SSL inspection).
@TingluoHuang, thank you for support.

**Comment by TingluoHuang** [comment]
another way might be set env variable `NODE_TLS_REJECT_UNAUTHORIZED=0` on the agent machine and restart the agent. the environment variable should allow node.js skip SSL validation error.
but, i am not sure whether that is what you want.

**Comment by ShadySQL** [comment]
and what could be the env variable name so the agent gets it?

**Comment by TingluoHuang** [comment]
@ShadySQL agent gets what?

**Comment by TingluoHuang** [comment]
I am closing this issue as the original issue has been mitigated by disable SSL inspection for agent connect to VSTS. please let me know if more help is needed.

**Comment by greektreat** [comment]
> i am a MS employee. you can send any information that you think is sensitive to `tihuang@microsoft.com`

You know that is also not acceptable to asked someone to send by email personal info. Email is not secure
