### ISSUE TITLE
DirectoryInfo.Delete() called with no args, throws IOException due to files present when trying to delete.

### ISSUE THREAD

**Issue by MattGal** [Microsoft/vsts-agent#918]
If you simply write some code that does the following, where somePath is a folder containing subfolders and files:

```
            DirectoryInfo d = new DirectoryInfo(somePath);
            d.Delete();

```
You will get the exact same exception listed below.  We're seeing this regularly in the "Get sources" step of our VSTS agent builds.  Upon inspecting the build agents, we do not find handles or processes still holding anything open on the workspaces used.  This is challenging to solve since this step is the first thing that runs before anything from our repository can run.  

Simply changing the d.Delete(); to d.Delete(true); solves the problem.
Note the following usages of DirectoryInfo.Delete():
https://github.com/Microsoft/vsts-agent/blob/master/src/Microsoft.VisualStudio.Services.Agent/Util/IOUtil.cs#L157
https://github.com/Microsoft/vsts-agent/blob/master/src/Microsoft.VisualStudio.Services.Agent/Util/IOUtil.cs#L206

There may be some good reason to use this very-likely-to-throw overload of the function, but perhaps there could at least be some fallback behavior?

## **Have you try trouble shooting doc?**
Link to trouble shooting doc: https://www.visualstudio.com/en-us/docs/build/troubleshooting
Yes.

## **Agent version and platform**
2.109.1
<br>
OS of the machine running the agent? Windows Server 2012 R2 DataCenter
<br>
## **VSTS type and version**
VisualStudio.com
<br>
If On-Prem TFS, which release, 2015 RTM/QU1/QU2? N/A
<br>
If VisualStudio.com, what is your account name? http://devdiv.visualstudio.com
<br>
## **What's not working?**  Please include error messages and screenshots

VSTS Agent uses DirectoryInfo.Delete() with no args.  This will throw the exact exception printed below from our logs if called with no arguments on a directory containing files, **even if these files have no handles open to them.**

Usages of DirectoryInfo.Delete():

https://github.com/Microsoft/vsts-agent/blob/master/src/Microsoft.VisualStudio.Services.Agent/Util/IOUtil.cs#L157
https://github.com/Microsoft/vsts-agent/blob/master/src/Microsoft.VisualStudio.Services.Agent/Util/IOUtil.cs#L206

Example of log issue:

[2017-04-11 21:59:01Z ERR  StepsRunner] Caught exception from step: System.IO.IOException: The directory is not empty
   at System.IO.Win32FileSystem.RemoveDirectoryHelper(String fullPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Win32FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at Microsoft.VisualStudio.Services.Agent.Util.IOUtil.DeleteDirectory(String path, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildDirectoryManager.DeleteDirectory(IExecutionContext executionContext, String description, String path)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildDirectoryManager.CreateDirectory(IExecutionContext executionContext, String description, String path, Boolean deleteExisting)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildDirectoryManager.PrepareDirectory(IExecutionContext executionContext, ServiceEndpoint endpoint, ISourceProvider sourceProvider)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildJobExtension.<PrepareAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtensionRunner.<RunAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunAsync>d__0.MoveNext()
[2017-04-11 21:59:01Z INFO StepsRunner] Step result: Failed

<br>
## **Agent and Worker's diag log**

Logs are located at the `_diag` under agent root folder, agent log prefix with `Agent_`, worker log prefix with `Worker_`. all sensitive information should already be masked out, please double check before paste here. 

[2017-04-11 21:58:43Z INFO TaskManager] Task already downloaded.
[2017-04-11 21:58:43Z INFO TaskManager] Ensuring task exists: ID 'c6c4c611-aa2e-4a33-b606-5eaba2196824', version '1.113.0', name 'MSBuild', directory 'E:\A\_work\_tasks\MSBuild_c6c4c611-aa2e-4a33-b606-5eaba2196824\1.113.0'.
[2017-04-11 21:58:43Z INFO TaskManager] Task already downloaded.
[2017-04-11 21:58:43Z INFO StepsRunner] Processing step: DisplayName='Get Sources', AlwaysRun=False, ContinueOnError=False, Critical=True, Enabled=True, Finally=False
[2017-04-11 21:58:43Z INFO StepsRunner] Starting the step.
[2017-04-11 21:58:43Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Worker.Build.ISourceProvider'
[2017-04-11 21:58:43Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.ExternalGitSourceProvider, Agent.Worker
[2017-04-11 21:58:43Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.GitHubSourceProvider, Agent.Worker
[2017-04-11 21:58:43Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.SvnSourceProvider, Agent.Worker
[2017-04-11 21:58:43Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.TfsGitSourceProvider, Agent.Worker
[2017-04-11 21:58:43Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.TfsVCSourceProvider, Agent.Worker
[2017-04-11 21:58:43Z INFO BuildDirectoryManager] Checking if build directory exists: 'E:\A\_work\70'
[2017-04-11 21:58:45Z INFO JobServerQueue] Try to append 1 batches web console lines, success rate: 1/1.
[2017-04-11 21:59:01Z ERR  StepsRunner] Caught exception from step: System.IO.IOException: The directory is not empty
   at System.IO.Win32FileSystem.RemoveDirectoryHelper(String fullPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Win32FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at Microsoft.VisualStudio.Services.Agent.Util.IOUtil.DeleteDirectory(String path, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildDirectoryManager.DeleteDirectory(IExecutionContext executionContext, String description, String path)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildDirectoryManager.CreateDirectory(IExecutionContext executionContext, String description, String path, Boolean deleteExisting)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildDirectoryManager.PrepareDirectory(IExecutionContext executionContext, ServiceEndpoint endpoint, ISourceProvider sourceProvider)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildJobExtension.<PrepareAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtensionRunner.<RunAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunAsync>d__0.MoveNext()
[2017-04-11 21:59:01Z INFO StepsRunner] Step result: Failed

**Comment by ericsciple** [comment]
can you try updating your agent. i fixed a bug in deletefiles related to symlinks iirc and i'm pretty sure it was after m109

you can update the pool from the admin pool page by right clicking the pool and updating all agents in the pool

**Comment by ericsciple** [comment]
Also 109 is pretty old at this point. Even if it's not the bug I'm remembering, there may have been other fixes.

**Comment by MattGal** [comment]
@ericsciple that's a fairly large undertaking for us but I can broach it with my team.  However, even looking at the head of master yesterday the problem I call out (specifically that if ANY files exist in the directory you're calling DirectoryInfo.Delete() on the exact exception we're noting happens) would still happen if any contents existed in such a directory.  How can you be certain that this is not the problem?

**Comment by ericsciple** [comment]
It's only a right click from the web UI. Or do you have many pools, or very many agents that reverting to 109 in the event something goes wrong would be a big undertaking? Even with the change you are proposing, it will require an agent update anyway to get the change. So why not try latest version first?

I'm hesitant to blindly set recursive=true when I don't understand what is going on, no one else is running into this issue, and it may already have been fixed. You are on an agent 4-5 months old and we release every 3 weeks. I know at least one fix went into the delete logic.

**Comment by MattGal** [comment]
Understood, trying this now.  As I understand it, we have lots of builds we need to not break and basically the main resistance is the lack of an ability to roll back if a new agent version brings a new problem.  Since there's clearly a fix in Enumerate() I have good hope of this solving the problem.

**Comment by ericsciple** [comment]
assuming that worked
